functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или
    категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать
    подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и
    просматривать содержимое корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для
    скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Сайт должен иметь мобильную версию
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - При отсутствие товара в магазине выводить кнопку заказать вместо купить
  - Товары в корзине авторизованных пользователей должны храниться длительное
    время, например пол года, пока они не удалят их или не купят
  - Цена по скидки должна явно отображаться, например: зачеркнутая старая цена, а рядом новая
  - Отображать у товаров сообщение "нет в наличии" если его нет на складе и нет
    возможности заказать товар.
  - В полях "от" и "до" раздела цены на сайте товаров, выводить фоном фактическую минимальную стоимость товара из всех товаров на странице (с учётом скидки)
